---
title: "CRRC Jaccard Index"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
library(dplyr)
library(psych)
library(ggplot2)
library(vegan)
```

```{r, message=F}
load("/Volumes/Anne/Harvard/Teams/Teams/d.Rdata")
```

```{r, message=F}
d <- d[with(d, order(tid, pid, day, type)),]
```

Select in-person interactions
```{r, message=F}
d_int <- d %>%
  mutate(s.ip_1 = ifelse(s.im_1 == 1, 1, NA),
         s.ip_2 = ifelse(s.im_2 == 1, 1, NA),
         s.ip_3 = ifelse(s.im_3 == 1, 1, NA),
         s.ip_4 = ifelse(s.im_4 == 1, 1, NA),
         s.ip_5 = ifelse(s.im_5 == 1, 1, NA),
         s.ip_6 = ifelse(s.im_6 == 1, 1, NA),
         s.ip_7 = ifelse(s.im_7 == 1, 1, NA))
```

Calculate lags 
```{r, message=F}
d_int <- d_int %>%
  group_by(pid, day) %>%
  mutate(s.ip_1.lag = lag(s.ip_1, n=1L, default=NA),
         s.ip_2.lag = lag(s.ip_2, n=1L, default=NA),
         s.ip_3.lag = lag(s.ip_3, n=1L, default=NA),
         s.ip_4.lag = lag(s.ip_4, n=1L, default=NA),
         s.ip_5.lag = lag(s.ip_5, n=1L, default=NA),
         s.ip_6.lag = lag(s.ip_6, n=1L, default=NA),
         s.ip_7.lag = lag(s.ip_7, n=1L, default=NA)) %>%
  ungroup()
```

Make two data sets and recode NAs into 0
```{r, message=F}
d_int1 <- d_int %>%
  select(s.ip_1:s.ip_7)

d_int1 <- d_int1 %>% replace(is.na(.), 0)

d_int2 <- d_int %>%
  select(s.ip_1.lag:s.ip_7.lag)

d_int2 <- d_int2 %>% replace(is.na(.), 0)
```

Calculate Jaccard index with vegdist from vegan package
```{r, message=F}
vegdist(rbind(unlist(d_int1, use.names=F), unlist(d_int2, use.names=F)), method="jaccard")
```

= 0.88
