---
title: "CRRC Interaction Variability"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=F}
library(knitr)
library(dplyr)
library(psych)
library(lme4)
library(ggplot2)
```

```{r, message=F}
load("d.Rdata")
```

Count of team sizes
```{r}
d %>%
  group_by(team) %>%
  arrange(desc(pid)) %>%
  slice(1) %>%
  ungroup() %>%
  ggplot(aes(x = team_size)) +
  geom_histogram()
```

Calculate the total number of interaction partners
```{r, message=F}
d <- d %>%
  rowwise() %>% 
  mutate(s.ip_t = sum(s.ip_1, s.ip_2, s.ip_3, s.ip_4, s.ip_5, s.ip_6, s.ip_7, na.rm=T))
```

Plot mean and sd of total number of interaction partners per day and type, and for interactions with each individual team member
```{r, message=F}
#Total
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_t, na.rm=T),
            q = sd(s.ip_t, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 1
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_1, na.rm=T),
            q = sd(s.ip_1, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 2
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_2, na.rm=T),
            q = sd(s.ip_3, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 3
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_3, na.rm=T),
            q = sd(s.ip_3, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 4
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_4, na.rm=T),
            q = sd(s.ip_4, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 5
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_5, na.rm=T),
            q = sd(s.ip_5, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 6
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_6, na.rm=T),
            q = sd(s.ip_6, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

#Team member 7
d %>%
  group_by(day, type) %>%
  summarize(p = mean(s.ip_7, na.rm=T),
            q = sd(s.ip_7, na.rm=T)) %>%
  ggplot(aes(x=day, y=p)) + 
  geom_point() + 
  geom_line(aes(group=type, color=type)) +
  geom_errorbar(aes(ymin = p - q, ymax = p + q, width = .2))

```

Empty multilevel model to estimate within person variance
```{r, message=F}
#Total 
summary(lmer(s.ip_t ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 1 
summary(lmer(s.ip_1 ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 2
summary(lmer(s.ip_2 ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 3
summary(lmer(s.ip_3 ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 4
summary(lmer(s.ip_4 ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 5
summary(lmer(s.ip_5 ~ 1 + (1 | team) + (1 | pid), data = d))

#Team member 6
summary(lmer(s.ip_6 ~  + (1 | team) + (1 | pid), data = d))

#Team member 7
summary(lmer(s.ip_6 ~  + (1 | team) + (1 | pid), data = d))
```


```{r}
my.mssd <- function(data)
{
    diffToNext<-data[2:length(data)]-data[1:(length(data)-1)] #this computes the difference between each value and the next
    diffToNext2<-diffToNext^2                  #this squares the difference
    SSdiff<- sum(diffToNext2,na.rm=TRUE)       #this takes the sum of the squared differences
    denominator<-sum(!is.na(diffToNext))       #this computes the number of non-missing elements (denominator)
                                               #which corresponds to the t-1 value
    mssd<-SSdiff/denominator                   #this computes the MSSD
    return(mssd)
}
```

```{r}
mssd.stats <- d %>%
  group_by(pid) %>%
  summarise(mssd = mssd(s.ip_t))
  
mssd(d[which(d$pid == 100101),]$s.ip_t)
```




